'''
https://www.codewars.com/kata/5830195755f28edad4000081/train/python
'''


def get_row(n):
    dict = {
        1: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
        2: 'BBCDEFGHIJKLMNOPQRSTUVWXYZ',
        3: 'CCCDEFGHIJKLMNOPQRSTUVWXYZ',
        4: 'DDDDEFGHIJKLMNOPQRSTUVWXYZ',
        5: 'EEEEEFGHIJKLMNOPQRSTUVWXYZ',
        6: 'FFFFFFGHIJKLMNOPQRSTUVWXYZ',
        7: 'GGGGGGGHIJKLMNOPQRSTUVWXYZ',
        8: 'HHHHHHHHIJKLMNOPQRSTUVWXYZ',
        9: 'IIIIIIIIIJKLMNOPQRSTUVWXYZ',
        10: 'JJJJJJJJJJKLMNOPQRSTUVWXYZ',
        11: 'KKKKKKKKKKKLMNOPQRSTUVWXYZ',
        12: 'LLLLLLLLLLLLMNOPQRSTUVWXYZ',
        13: 'MMMMMMMMMMMMMNOPQRSTUVWXYZ',
        14: 'NNNNNNNNNNNNNNOPQRSTUVWXYZ',
        15: 'OOOOOOOOOOOOOOOPQRSTUVWXYZ',
        16: 'PPPPPPPPPPPPPPPPQRSTUVWXYZ',
        17: 'QQQQQQQQQQQQQQQQQRSTUVWXYZ',
        18: 'RRRRRRRRRRRRRRRRRRSTUVWXYZ',
        19: 'SSSSSSSSSSSSSSSSSSSTUVWXYZ',
        20: 'TTTTTTTTTTTTTTTTTTTTUVWXYZ',
        21: 'UUUUUUUUUUUUUUUUUUUUUVWXYZ',
        22: 'VVVVVVVVVVVVVVVVVVVVVVWXYZ',
        23: 'WWWWWWWWWWWWWWWWWWWWWWWXYZ',
        24: 'XXXXXXXXXXXXXXXXXXXXXXXXYZ',
        25: 'YYYYYYYYYYYYYYYYYYYYYYYYYZ',
        26: 'ZZZZZZZZZZZZZZZZZZZZZZZZZZ'
    }

    if n <= 26:
        return dict[n]
    elif n % 26 == 0:
        return dict[26]
    elif n > 26:
        return dict[n % 26]